#!/bin/bash

ip=$1
comm=$2
n_ports=$3

if [[ $ip == '' || $comm == '' || $n_ports == '' ]]; then
    echo "You must give ip, community_name, number of switch ports"
    exit 1
fi


s_ports=$(/usr/lib/nagios/plugins/check_netgear_switch -h $ip -c $comm -s ports -n $n_ports | grep Up | cut -d " " -f2 | sort -n)

exit_code=0
res=""
for i in $s_ports; do
    rel=$(snmpwalk -v1 -c $comm $ip iso.3.6.1.2.1.16.1.1.1.13.$i)

    if [[ $(echo $rel | grep -e "Counter32: 1[0-9][0-9][0-9]") != '' ]]; then
        res="${res}\nPort_$i: $(echo $rel |cut -d ':' -f2) frame collisions detected"
        exit_code=2
    fi

done

if [[ $res == '' ]]; then
    echo -e "Ports OK - no frame collisions"
    exit 0
else
    echo -e "$res"
    exit $exit_code
fi
